test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: diary_test
  username: root
  password:
  host: <%= ENV["DB_HOST"]%>